export const RECEIVED_PHOTOS = 'RECEIVED_PHOTOS';
export const RECEIVED_POSTS = 'RECEIVED_POSTS';
export const RECEIVED_ALBUMS = 'RECEIVED_ALBUMS';
export const RECEIVED_COMMENTS = 'RECEIVED_COMMENTS';
export const RECEIVED_USERS = 'RECEIVED_USERS';

export const BOOTSTRAP_LANDING = 'BOOTSTRAP_LANDING';
